### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'jquery.ui.datepicker')

### ISSUE THREAD

**Issue by alepore** [vinsol/spree_bank_transfer#19]
Uhm not sure why i'm getting this now.
Shouldn't this be `jquery-ui/datepicker` ?

**Comment by moody404** [comment]
i also have the same issue here

**Comment by moody404** [comment]
I just fix it by install the gem 'jquery-ui-rails' . it


and change the js file in. your path might be different 

/home/moody404/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spree-bank-transfer-2.3.0/app/assets/javascripts/store/spree_bank_transfer.js.erb


so change this line 
 //= require jquery.ui.datepicker 
to
//= require jquery-ui
